spring.application.name=wayscout
weather.api.key=${WEATHER_API_KEY:eee007c1e3d1411c9ef230507261304}
tomtom.api.key=${TOMTOM_API_KEY:v7PaARRtlqH6KCuXyUYBGsQelxBK15Zu}
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173
